### ISSUE TITLE
ESP webserver-websocket wifi -serial bridge

### ISSUE THREAD

**Issue by mkeyno** [tdmts/Tdmts.ESP8266#1]
sorry to open ticket for my question but honestly I couldn't figure out which part of your code would be help me out, actually I intend to use my special webserver-websocket program(Arduino IDE) in the ESP module to made Wifi -serial bridge with simple C# application , may I have your advice which part of source code would be helpful for me?
BR

**Comment by tdmts** [comment]
Hi there

I think you should take a look at [http://tdmts.net/2017/02/04/controlling-an-arduino-with-a-wifi-esp8266-adapter-using-a-windows-10-universal-app/](http://tdmts.net/2017/02/04/controlling-an-arduino-with-a-wifi-esp8266-adapter-using-a-windows-10-universal-app/) to help you out. 
If you still have questions, you can use the comments section there.

Good luck and have fun!

Tom

**Comment by mkeyno** [comment]
thanks for those info , I place my comment there and for record I pasted here as well

BR

> 
thanks for sharing the project , however it used the normal webserver  which is so slow and probably so many time out will happen if encounter with busy serial bus , to solve this phenomenon I launch websoket server to keep the line alive , I really appreciated if you could extend your example with C# client websoket as well
